baseurl = "https://gophercon.sg/"
languageCode = "en-us"
title = "GopherCon Singapore"
theme = "hugo-creative-theme"
# ignoreFiles = ["\\.md$"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "GopherCon Singapore"
	description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GopherCon Singapore"

		[params.navigation.links]
			#about    = "About"
			speakers  = "Schedule"
			#events    = "Events"
			venue     = "Venue"
			workshop = "Workshop"
      #partners = "Partners"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		buttonText = "Get Tickets"

	# About section
	[params.about]
    headline    = "The inaugural Go conference in Singapore!"


	# Speakers section
	[params.speakers]
		# headline = "At your service"
    [params.speakers.speaker1]
       profile = "Robert-Griesemer.jpg"
       name = "Robert Griesemer"
       company = "some company"
       bio = "Awesome Hacker"
       talk = "name of the talk"

    [params.speakers.speaker2]
       profile = "Robert-Griesemer.jpg"
       name = "Dave Cheney"
       company = "some company"
       bio = "Awesome Hacker"
       talk = "name of the talk"

  [params.events]
      headline    = "We've got what you need!"
      description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
      buttonText  = "Get started!"

  # Schedule section
  [params.schedule]

  # Venue section
	[params.venue]
		headline = "The Venue"

	# Partners section
	[params.partners]
		#headline = "Proudly sponsored by:"
		headline = "Sponsors"
		description = "Interested in becoming a sponsor? [Get in touch](mailto:hello@gophercon.sg)"

	# Footer section
	[params.credits]
    description = "hello@gophercon.sg"
