baseurl = "https://2017.gophercon.sg/"
languageCode = "en-us"
title = "GopherCon Singapore"
theme = "hugo-creative-theme"
# ignoreFiles = ["\\.md$"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "GopherCon Singapore"
	description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GopherCon Singapore"

		[params.navigation.links]
			#about    = "About"
			speakers  = "Speakers"
      talks     = "Talks"
			#events    = "Events"
			venue     = "Venue"
			workshop = "Workshop"
      #partners = "Partners"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		buttonText = "Get Tickets"

	# About section
	[params.about]
    headline    = "The inaugural Go conference in Singapore!"


	# Speakers section
	[params.speakers]
    [params.speakers.speaker]
       profile = "Robert-Griesemer.jpg"
       name = "Robert Griesemer"
       fragmentId = "robert-griesemer"
       brand = "https://github.com/griesemer"
       bio = "Robert is one of the creators of the Go programming language. Before Go, he was involved in the design and implementation of Google's V8 JavaScript engine, the domain-specific language Sawzall, the Java HotSpot virtual machine, and Strongtalk, a high-performance Smalltalk system. Once upon a time, he built a vectorizing compiler for the iconic Cray X-MP. Robert works at Google in Mountain View, California, and loves energy-efficient things that \"just work\"."

    [params.speakers.speaker1]
       profile = "dave_cheney.jpg"
       name = "Dave Cheney"
       fragmentId = "dave-cheney"
       brand = "https://twitter.com/davecheney"
       bio = "David is a programmer, public speaker, and author from Sydney, Australia. David has been a contributor to the Go project since February 2011 and is an organiser of GopherCon Denver. David currently works at Atlassian building Kubernetes infrastructure for their internal platform as a service."

    [params.speakers.speaker2]
       profile = "bill.jpg"
       name = "William Kennedy"
       fragmentId = "william-kennedy"
       brand = "https://twitter.com/goinggodotnet"
       bio = "William Kennedy is a managing partner at Ardan Studio in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog [GoingGo.Net](http://goinggo.net), and a founding member of [GoBridge](https://golangbridge.org/) which is working to increase Go adoption through diversity."

    [params.speakers.speaker3]
       profile = "ajey-gore.jpg"
       name = "Ajey Gore"
       fragmentId = "ajey-gore"
       brand = "https://twitter.com/goinggodotnet"
       bio = "Ajey is the Group CTO of [Go-Jek](https://www.go-jek.com/). With 17 years of experience in building core technology strategy across diverse domains, Ajey has helped several businesses through technology transformations @ [ThoughtWorks](https://www.thoughtworks.com/) and [CodeIgnition](https://twitter.com/codeignition). Ajey is the founder of CodeIgnition and an active influencer in the technology community."
       talk = "test2"

    # --------------------------------------

    [params.speakers.speaker_talk_a]
       profile = "gopher_merlion.png"
       name = "Do Xuan Huy"
       fragmentId = "do-xuan-huy"
       brand = "https://twitter.com/dxhuy"
       bio = "Huy's a software engineer working at LINE corp in the group called engineering effeciency. His group mission is to reduce painful point of development process, building tools which make software development and shipment easier, more fun and safer. Previous to golang, he's a heavy user of Ruby, and also one of founder of Vietnam biggest Ruby user group. He'd also co-founded one of biggest social platform for software engineer in Vietname: kipalog (https://kipalog.com)"
       title = "How golang help us to solve organization scale problem at LINE"
       abstract = "Grow to 400 millions registered users in only 5 years lead to not only scale problem of system, but also scale problem of organization. In LINE we solve that problem by building tools which improve engineer productivity and unify process. In this presentation i will introduce about those tools."

    [params.speakers.speaker_talk_b]
       profile = "gopher_merlion.png"
       name = "Chewxy"
       fragmentId = "chewxy"
       brand = "https://twitter.com/chewxy"
       bio = "Xuanyi co-founded a startup that uses natural language to perform data science analysis."
       title = "Writing Efficient Generic Multidimensional Slices"
       abstract = "Go has no generics. That makes things a lot harder. Or does it? This talk looks at various attempts in creating multidimensional arrays (think matrices and tensors) which are useful in deep learning and mathematics heavy applications. Even better - making them generic so they can take any type"

    [params.speakers.speaker_talk_c]
       profile = "gopher_merlion.png"
       name = "Matthew Campbell"
       fragmentId = "matthew-campbell"
       brand = "https://twitter.com/kanwisher"
       bio = "Matthew Campbell is a Microservices scalability expert at DigitalOcean where he builds the future of cloud services. He is writting a book called “Microservices in Go”. He recently presented at GoLang UK, PromConf Berling, and Surge India, and blogs at “kanwisher.com”:http://kanwisher.com. Matthew was a founder of “Errplane”:http://errplane.com/ and “Langfight”:http://www.langfight.com. In the past he worked at Thomson Reuters, Bloomberg, Gucci, and Cartoon network."
       title = "Distributed Scheduler Hell"
       abstract = "Containers are the future for all Microservice based apps. Where do you deploy them? How do you manage them? This talk will walk the audience through how distributed schedulers are built, and how the popular ones work. We will drill into details of how to build a distributed scheduler."

    [params.speakers.speaker_talk_d]
       profile = "gopher_merlion.png"
       name = "Dave Appleton"
       fragmentId = "dave-appleton"
       brand = "https://twitter.com/AppletonDave"
       bio = "Dave Appleton has been messing around with things since sometime before the dawn of time.  Mentored by people with more technical expertise than interpersonal skills and business sense, Dave started programming in 1968 in FORTRAN, building audio systems about the same time and messing with digital logic in 1976.  In the intervening time he has built world beating test systems, co-designed award winning products, run his own instrumentation company for over fifteen years, learned and actually used more than two dozen programming languages at a professional level, and taught courses from hobby to degree level on subjects as diverse as IOT, e-commerce and Image Processing. For the last three years he has been working on crypto currencies and financial technology."
       title = "Getting started on Ethereum for Go programmers"
       abstract = "Learn how a Go programmer can get started with the hottest blockchain technology on the block with an easy tutorial that will demonstrate creating a simple smart contract and accessing it from a Go server as well as an Ethereum Wallet.  "

    [params.speakers.speaker_talk_e]
       profile = "gopher_merlion.png"
       name = "Ryan Law"
       fragmentId = "ryan-law"
       brand = ""
       bio = "Ryan is currently a Site Reliability Engineer at Grab. Being one of Grab’s early engineers, he has extensive knowledge of Grab’s system and he makes use of it by diving deep into different technical problems on a daily basis. Before switching over to his current role, Ryan led the web frontend and the Ruby on Rails teams at Grab."
       title = "Distributed Tracing in Grab"
       abstract = "In Grab, we went from monolithic services to multiple smaller services in Go and we missed the ability to have detailed transaction traces of our code. In this talk, we will show you how we are re-implementing this ability in Go, a language that does not support thread-locals"

    [params.speakers.speaker_talk_f]
       profile = "gopher_merlion.png"
       name = "Ent"
       fragmentId = "ent"
       brand = ""
       bio = "I am a Software Developer with over 8 years of experience where I have majorly worked with Python for Startups. Apart from building the software for the clients, one major issue I had to repeatedly deal with was the way Python was designed and how I had to fight against it to achieve the desired functionality. This led me to read and understand how Python internals work; which in turn only made me feel the need for a more elegantly designed runtime.  Initially I did not appreciate Go but the more I read about its design, the more it felt like a properly done language/runtime. After using it for a few small projects, it was easier to appreciate it and propose using it at work. I have learned a decent bit and continue to learn the interesting parts of Go but perhaps the path could have been easier if certain topics were more accessible.  Purpose of my Talk My proposed talk is about topics which I feel if I had a consolidated article/talk on, it would have been easier for me to learn faster while making fewer mistakes along the way. I believe that I might not be the only one who would benefit from these topics and I would like to present them to Go community if possible."
       title = "Runtime & Concurrency in Go."
       abstract = "One popular feature of Go is Goroutine. Yet, not everyone knows how Goroutines work under the hood or what factors need to be taken into consideration when working with them. This talk attempts to explain rationale behind Green Threads & Coroutines and how Goroutines are linked to them."

    [params.speakers.speaker_talk_g]
       profile = "gopher_merlion.png"
       name = "Manish Rai Jain"
       fragmentId = "maish-rai-jain"
       brand = "https://twitter.com/manishrjain"
       bio = "Manish is the founder of Dgraph, a distributed graph database built for production. He got thrust into distributed systems right out of college, working on real-time web indexing system at Google. He then led various projects to consolidate and serve knowledge graph right behind web search.  Implementing GTD and Zero Waste practices, Manish is into efficient and minimalist living. He loves cycling, swimming and ultra-light traveling."

       title = "Dgraph - A distributed graph database written in Go"
       abstract = "Dgraph is a native and distributed graph database written entirely in Go. Efficient distributed joins is a hard problem and Dgraph tackles it head on. Since v0.1 release in Dec’15, Dgraph has seen a lot of activity, reaching close to 2000 Github stars and to front page of Hacker News multiple times."

    [params.speakers.speaker_talk_h]
       profile = "gopher_merlion.png"
       name = "Choon Keat"
       fragmentId = "choon-keat"
       brand = "https://twitter.com/choonkeat"
       bio = "Started the Singapore Ruby Brigade, worked at Slideshare, believes strongly in and contributes to open source. Now available in Go."

       title = "TDD for those who don't need it"
       abstract = "For the longest time, I don’t write tests.  Writing tests is chore, waste of time, doesn’t GTD. The snobbery of test community only turned me off even more; discouraging good developers from trying TDD.  Now I write tests first. This talk explains what clicked for me (and maybe you will too)"

    [params.speakers.speaker_talk_i]
       profile = "gopher_merlion.png"
       name = "Kenneth Shaw"
       fragmentId = "kenneth-shaw"
       brand = "https://github.com/knq"
       bio = "Kenneth “Ken” Shaw is a veteran systems developer, technologist, and entrepreneur and has worked with a number of companies/startups to build out large-scale Go applications, their associated architecture, automation, and deployments. Ken is the former CTO of Multiply.com, and previously built and sold two different tech companies. Currently, Ken is the Founder/CTO of Brankas, a company aiming to change the way banking is done in South East Asia."

       title = "chromedp: A New Way to Drive the Web"
       abstract = "Introduction to chromedp: a faster, simpler way to drive browsers in Go using the Chrome Debugging Protocol (for Chrome, Edge, Safari, etc) without external dependencies. Includes overview of using chromedp to rapidly author complex task hierarchies for scraping and unit testing/profiling web apps."

    # --------------------------------------
    [params.speakers.speaker_talk_z]
       profile = "gopher_merlion.png"
       name = "More Awesome Gophers"
       caption = "To be announced"


  [params.events]
      headline    = "We've got what you need!"
      description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
      buttonText  = "Get started!"

  # Talks section
  [params.conference]
      header = "Conference"
      date = "Friday, 26th May"
      type = "Talks"

    [params.conference.talks]
      [params.conference.talks.talk01]
        title = "$GOPHERCONSG/doors/open"
        class = "timeline-mono-header"
        timerange = "8.00am to 9.00am"

      [params.conference.talks.talk02]
        title = "Keynote"
        class = "timeline-sub-header"
        timerange = "9.00am to 9.30am"
        profile = "gopher_merlion.png"
        name = "Awesome gopher"

      [params.conference.talks.talk03]
        title = "Awesome talk title"
        class = "timeline-sub-header"
        timerange = "9.30am to 10.00am"
        profile = "gopher_merlion.png"
        name = "Awesome gopher"
        talk = "Information about the talk"

  # Workshop section
  [params.workshop]
    timerange = "9.00am to 5.30pm"
    title = "Ultimate Go Workshop"
    date = "Thursday, 25th May"
    venue = "Amazon Web Services, 23 Church Street, #10-01, Singapore 049481"
    venueinfo = "Lunch is provided"
    type = "Workshop"
    instructor = "William Kennedy"
    profile = "bill.jpg"
    twitterbrand = "https://twitter.com/goinggodotnet"
    bio = "William Kennedy is a managing partner at Ardan Studio in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog [GoingGo.Net](http://goinggo.net), and a founding member of [GoBridge](https://golangbridge.org/) which is working to increase Go adoption through diversity."

  # Venue section
	[params.venue]
		headline = "The Venue"

	# Partners section
	[params.partners]
		headline = "Partners"
		description = "Interested in becoming a partner? [Get in touch](mailto:hello@gophercon.sg)"

	# Footer section
	[params.credits]
    description = "hello@gophercon.sg"
