baseurl = "https://2017.gophercon.sg/"
languageCode = "en-us"
title = "GopherCon Singapore"
theme = "hugo-creative-theme"
# ignoreFiles = ["\\.md$"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "GopherCon Singapore"
	description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GopherCon Singapore"

		[params.navigation.links]
			#about    = "About"
			speakers  = "Speakers"
      talks     = "Talks"
			#events    = "Events"
			venue     = "Venue"
			workshop = "Workshop"
      #partners = "Partners"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		buttonText = "Get Tickets"

	# About section
	[params.about]
    headline    = "The inaugural Go conference in Singapore!"


	# Speakers section
	[params.speakers]
    [params.speakers.speaker]
       profile = "Robert-Griesemer.jpg"
       name = "Robert Griesemer"
       fragmentId = "robert-griesemer"
       brand = "https://github.com/griesemer"
       bio = "Robert is one of the creators of the Go programming language. Before Go, he was involved in the design and implementation of Google's V8 JavaScript engine, the domain-specific language Sawzall, the Java HotSpot virtual machine, and Strongtalk, a high-performance Smalltalk system. Once upon a time, he built a vectorizing compiler for the iconic Cray X-MP. Robert works at Google in Mountain View, California, and loves energy-efficient things that \"just work\"."

    [params.speakers.speaker1]
       profile = "dave_cheney.jpg"
       name = "Dave Cheney"
       fragmentId = "dave-cheney"
       brand = "https://twitter.com/davecheney"
       bio = "David is a programmer, public speaker, and author from Sydney, Australia. David has been a contributor to the Go project since February 2011 and is an organiser of GopherCon Denver. David currently works at Atlassian building Kubernetes infrastructure for their internal platform as a service."

    [params.speakers.speaker2]
       profile = "bill.jpg"
       name = "William Kennedy"
       fragmentId = "william-kennedy"
       brand = "https://twitter.com/goinggodotnet"
       bio = "William Kennedy is a managing partner at Ardan Studio in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog [GoingGo.Net](http://goinggo.net), and a founding member of [GoBridge](https://golangbridge.org/) which is working to increase Go adoption through diversity."

    [params.speakers.speaker3]
       profile = "ajey-gore.jpg"
       name = "Ajey Gore"
       fragmentId = "ajey-gore"
       brand = "https://twitter.com/goinggodotnet"
       bio = "Ajey is the Group CTO of [Go-Jek](https://www.go-jek.com/). With 17 years of experience in building core technology strategy across diverse domains, Ajey has helped several businesses through technology transformations @ [ThoughtWorks](https://www.thoughtworks.com/) and [CodeIgnition](https://twitter.com/codeignition). Ajey is the founder of CodeIgnition and an active influencer in the technology community."

    [params.speakers.speaker_gopher]
       profile = "gopher_merlion.png"
       name = "More Awesome Gophers"
       caption = "To be announced"


  [params.events]
      headline    = "We've got what you need!"
      description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
      buttonText  = "Get started!"

  # Talks section
  [params.conference]
      header = "Conference"
      date = "Friday, 26th May"
      type = "Talks"

    [params.conference.talks]
      [params.conference.talks.talk01]
        title = "$GOPHERCONSG/doors/open"
        class = "timeline-mono-header"
        timerange = "8.00am to 9.00am"

      [params.conference.talks.talk02]
        title = "Keynote"
        class = "timeline-sub-header"
        timerange = "9.00am to 9.30am"
        profile = "gopher_merlion.png"
        name = "Awesome gopher"

      [params.conference.talks.talk03]
        title = "Awesome talk title"
        class = "timeline-sub-header"
        timerange = "9.30am to 10.00am"
        profile = "gopher_merlion.png"
        name = "Awesome gopher"
        talk = "Information about the talk"

  # Workshop section
  [params.workshop]
    timerange = "9.00am to 5.30pm"
    title = "Ultimate Go Workshop"
    date = "Thursday, 25th May"
    venue = "Amazon Web Services, 23 Church Street, #10-01, Singapore 049481"
    venueinfo = "Lunch is provided"
    type = "Workshop"
    instructor = "William Kennedy"
    profile = "bill.jpg"
    twitterbrand = "https://twitter.com/goinggodotnet"
    bio = "William Kennedy is a managing partner at Ardan Studio in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog [GoingGo.Net](http://goinggo.net), and a founding member of [GoBridge](https://golangbridge.org/) which is working to increase Go adoption through diversity."

  # Venue section
	[params.venue]
		headline = "The Venue"

	# Partners section
	[params.partners]
		headline = "Partners"
		description = "Interested in becoming a partner? [Get in touch](mailto:hello@gophercon.sg)"

	# Footer section
	[params.credits]
    description = "hello@gophercon.sg"
