baseurl = "https://2017.gophercon.sg/"
languageCode = "en-us"
title = "GopherCon Singapore"
theme = "hugo-creative-theme"
# ignoreFiles = ["\\.md$"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "GopherCon Singapore"
	description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GopherCon Singapore"

		[params.navigation.links]
			#about    = "About"
			speakers  = "Speakers"
			#events    = "Events"
			venue     = "Venue"
			workshop = "Workshop"
      #partners = "Partners"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		buttonText = "Get Tickets"

	# About section
	[params.about]
    headline    = "The inaugural Go conference in Singapore!"


	# Speakers section
	[params.speakers]
		# headline = "At your service"
#    [params.speakers.speaker1]
#       profile = "Robert-Griesemer.jpg"
#       name = "Robert Griesemer"
#       bio = "Awesome Hacker"
#       talk = "name of the talk"

    [params.speakers.speaker]
       profile = "dave_cheney.jpg"
       name = "Dave Cheney"
       fragmentId = "dave-cheney"
       brand = "https://twitter.com/davecheney"
       bio = "David is a programmer, public speaker, and author from Sydney, Australia. David has been a contributor to the Go project since February 2011 and is an organiser of GopherCon Denver. David currently works at Atlassian building Kubernetes infrastructure for their internal platform as a service."
       #talk = "Talk: To be announced"

    [params.speakers.speaker_gopher]
       profile = "gopher_merlion.png"
       name = "More Awesome Gophers"
       caption = "To be announced"

    [params.speakers.speaker2]
       profile = "bill.jpg"
       name = "William Kennedy"
       fragmentId = "william-kennedy"
       brand = "https://twitter.com/goinggodotnet"
       bio = "William Kennedy is a managing partner at Ardan Studio in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog [GoingGo.Net](http://goinggo.net), and a founding member of [GoBridge](https://golangbridge.org/) which is working to increase Go adoption through diversity."

  [params.events]
      headline    = "We've got what you need!"
      description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
      buttonText  = "Get started!"

  # Schedule section
  [params.schedule]

  # Venue section
	[params.venue]
		headline = "The Venue"

	# Partners section
	[params.partners]
		#headline = "Proudly sponsored by:"
		headline = "Sponsors"
		description = "Interested in becoming a sponsor? [Get in touch](mailto:hello@gophercon.sg)"

	# Footer section
	[params.credits]
    description = "hello@gophercon.sg"
